language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  fast_finish: true

services:
  - mysql
  - redis-server

before_script:
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --prefer-dist
  - composer require --dev friendsofphp/php-cs-fixer
  - composer require --dev php-coveralls/php-coveralls
  - wget https://github.com/phpstan/phpstan/releases/download/0.11.19/phpstan.phar
  - chmod +x ./phpstan.phar
  - mkdir -p build/logs

script:
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run --format txt
  - ./phpstan.phar analyze --level=max src/
  - vendor/bin/phpunit -c phpunit.xml.travis.dist
  - vendor/bin/php-coveralls -v --exclude-no-stmt

notifications:
  email: false
